// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/mytheresa/go-hiring-challenge/models"
	mock "github.com/stretchr/testify/mock"
)

// DataStore is an autogenerated mock type for the DataStore type
type DataStore struct {
	mock.Mock
}

// AddCategory provides a mock function with given fields: category
func (_m *DataStore) AddCategory(category models.AddCategory) error {
	ret := _m.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for AddCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.AddCategory) error); ok {
		r0 = rf(category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckProductExists provides a mock function with given fields: id
func (_m *DataStore) CheckProductExists(id uint) (bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CheckProductExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCategories provides a mock function with given fields: query
func (_m *DataStore) GetAllCategories(query *models.GetCategoryFilter) (*models.CategoryList, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 *models.CategoryList
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.GetCategoryFilter) (*models.CategoryList, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(*models.GetCategoryFilter) *models.CategoryList); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CategoryList)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.GetCategoryFilter) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllProducts provides a mock function with given fields: query
func (_m *DataStore) GetAllProducts(query *models.GetProductsFilter) (*models.ProductList, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 *models.ProductList
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.GetProductsFilter) (*models.ProductList, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(*models.GetProductsFilter) *models.ProductList); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ProductList)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.GetProductsFilter) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProduct provides a mock function with given fields: code
func (_m *DataStore) GetProduct(code string) (*models.Product, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Product, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Product); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDataStore creates a new instance of DataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataStore {
	mock := &DataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
